// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuvrKkLnCKceB7f-vIsPyPfBesr6Jqg3s',
    appId: '1:38240410420:android:6e8f2bea7785968915e361',
    messagingSenderId: '38240410420',
    projectId: 'gochon-app',
    storageBucket: 'gochon-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb_FxwZ_IMKdM5zk6eSOgIHzN_Gobhmmw',
    appId: '1:38240410420:ios:3f2d7408dda77b2e15e361',
    messagingSenderId: '38240410420',
    projectId: 'gochon-app',
    storageBucket: 'gochon-app.firebasestorage.app',
    iosBundleId: 'dev.gochonMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb_FxwZ_IMKdM5zk6eSOgIHzN_Gobhmmw',
    appId: '1:38240410420:ios:be79a8e86216ed2d15e361',
    messagingSenderId: '38240410420',
    projectId: 'gochon-app',
    storageBucket: 'gochon-app.firebasestorage.app',
    iosBundleId: 'com.example.gochonMobile',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuvrKkLnCKceB7f-vIsPyPfBesr6Jqg3s',
    appId: '1:38240410420:web:your-web-app-id',
    messagingSenderId: '38240410420',
    projectId: 'gochon-app',
    storageBucket: 'gochon-app.firebasestorage.app',
  );
}
